name: Main
concurrency:
  # 1 running pipeline per workflow per PR
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  # Running a new pipeline will cancel any running pipelines that belong to the above group
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  yarn_install_and_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/yarn-install-and-cache

  test:
    needs: yarn_install_and_cache
    uses: ./.github/workflows/test.yml
